CC = gcc
CFLAGS = -g -Wall
LDFLAGS = -lssl -lcrypto

quickxorhash: quickxor_bin.o quickxor.o
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

quickxor_bin.o: quickxor_bin.c
	$(CC) -c $^ -o $@

quickxor.o: quickxor.c
	$(CC) -c $^ -o $@

clean:
	rm -f *.o
	rm -f quickxorhash
